keys:
  - &laptop age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
  - &ocr1 age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
  - &tiny1 age1xrwyye8j3ha5amfppy6jfszusrkge0aly8qe6gwn9sezr5ec7gmqklvx0e
  - &tiny2 age1pl8fux4vzurj4l8hmtwqeeuzn5x5jmf6s6paekueawr760vyv94s8d0j4e
  - &rp age17ywcr7kkevqtmpgacj6mff7suqh570fglngz0x0c7l8lajr3gchq5yn29v
creation_rules:
  - path_regex: secrets.yml$
    key_groups:
      - age:
          - *ocr1
          - *tiny1
          - *tiny2
          - *laptop
  - path_regex: rp-sec.yml$
    key_groups:
      - age:
          - *laptop
          - *rp
