keys:
  - &laptop age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
  - &ocr1 age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
  - &tiny1 age1f2cy2lel6g6sadddnhqwmtsf2jtzqa2rp3qv6mf5w7d7wka84sks820s4u
  - &tiny2 age1pl8fux4vzurj4l8hmtwqeeuzn5x5jmf6s6paekueawr760vyv94s8d0j4e
  - &rp age1a6ssujp7yhqaxgehhana5f463axh3ksmytv7qa3y43z7wl28y3esv47mm6
creation_rules:
  - path_regex: secrets.yml$
    key_groups:
      - age:
          - *ocr1
          - *tiny1
          - *tiny2
          - *laptop
  - path_regex: rp-sec.yml$
    key_groups:
      - age:
          - *laptop
          - *rp
