pangolin-server-secret: ENC[AES256_GCM,data:aO2Shx3KAM13562psRSdjvQWYyTzTx7kRip9E7jnk+we8UxAaT8/FMB6nU096b4HmaeT7U3fy2LgGn0utsI6UA==,iv:MC1TP7hVsaQPAD984UUK+/d/gWLeZ2w3B32MQcWlTXQ=,tag:eFdLRB8geRSF3+IiC1A8Xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0OEQ3empmYmxTc25MZGFK
            N3ZBQ3g1TWExRzBVUkw5cEtPako3Wi9ybEVnCmpQaVd4NTQ5OExQY2FJTXljY0ly
            enZhNWFPNjlzN0UzSW5scWpIN0NJdkEKLS0tIGNUVTFaM3NURnRMdHRWdGIwR21U
            RzlHVEMvUEF5OXJOaWw2NjRiR05Bb0kK4lNJ0/V3tgnCeP7EkRJ3SwVaAzQ753pZ
            9NDNkfz3dEyozjqeTupG2WsmJBP3JPKSYr8TD0hQcSsqUnAnpziIFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTGh0VFJFcFR5Z2Z4NERV
            UFJSb0ZwV1Z1Ry90NnFDaE5BK1VkOTVpRVNRCjlTM0E4U05wT0Zzb3ZWTGo2dzNS
            eFc3MVE3ems0M2QxR2tyeEdwSkI1KzQKLS0tIEZiZ3V1TWkxK3U2dEYrUUNXdVNr
            UnJUQldFZmZSMzNsa0o5NFZ3NGM4bUUKcvaBo6bav1f8vKSethROB0v1YL/Zf5qa
            beCeRXXQVlhdba8eFta/3cfoIL8bHdv0M9TnIRfYq1HDNw9P4oH5kA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3gcq6a43fht8rt5k90k9ydlsr7d037lrqqx9lsyd92chfus6pss34q9jw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL2VPWlpldXpHYzVnTjBE
            MXc5Y0kwdlNLdXU3b1V3ZXpUcndRQzR3M0dnCnZrR0c4T0tKYVJkTjRaUDhBZTdq
            TmFhYXVudWZ1Q2dzU1Juc1lZbndzVE0KLS0tIE1McTlKQTl6RzFrVDNhVldyTEg1
            Y0wrZEtkVnViNFFGZXVZSzhQRWtiRVUK/iugNThPhdI2/AnDDaSSN9ejh9/XYcfR
            Yx9HkXp1c6zg1vKGMDoJHf//5EjpPqJ/eq6Cdm/LWABlyQGG7WrOGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV3ZkOFltcktFeGxDWkFY
            L2dibUtsS3dTdmlFVVBvOVNKMDNwMWpsQWxJCnNtcDBrUTlvYlBMcEJMZGRlTXNx
            LzRKNGlabWpIeDV3MER1akl5eDc3SWcKLS0tIEFDekR0MElzVkZqeDhtcjZ4akxq
            VDVTVzZQdktUUzlzaW45R0JEVmRFYkUKTik89Nu9wGupBwwGl6H6uF04yStVXObg
            7GnscA+k5aVfyQYX/e5fawngsRb1c8G0+0At5xdUDUIxt+CTKYIcWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-08-10T08:54:31Z"
    mac: ENC[AES256_GCM,data:5A3EmGrTMozOKfMpBy/CdtOjkQdO/0fDbFouRdfyuv4tnWU+3RtVZ8IIt5KUanIw3xsQUY9P4bEvNbw9/40B/ix2tfGOOQd31WjeZeQD60VuipyXs0jTSXNVcpm+I51i6R3cE5aZkzyzU0MXAf0dW2FM/b/2sUhoxlIFEhz47V0=,iv:eDzuk5l+f9YFcX8lb19K62ZQmd3cLMbO4OvUI8K3w9Y=,tag:20k//RVyWoi7yuKxGYfufQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
