name: Setup nix and cachix
description: setup nix and cachix
author: "Zbinden Yohan"
inputs:
  cacheName:
    required: true
    type: string
  setup-qemu:
    required: false
    type: boolean
    default: false
  cachixAuthToken:
    description: "the cachix auth token"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v3
      if: ${{ inputs.setup-qemu }}
    - uses: cachix/install-nix-action@v31
      name: Install
      with:
        extra_nix_config: |
          auto-allocate-uids = true
          configurable-impure-env = true
    - uses: cachix/cachix-action@v14
      with:
        name: ${{ inputs.cacheName }}
        authToken: ${{ inputs.cachixAuthToken }}
