name: Setup nix and cachix
description: setup nix and cachix
author: "Zbinden Yohan"
inputs:
  cacheName:
    required: true
    type: string
  cachixAuthToken:
    description: "the cachix auth token"
    required: true

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@v31
      name: Install
      with:
        extra_nix_config: |
          auto-allocate-uids = true
          configurable-impure-env = true
    - uses: cachix/cachix-action@v14
      with:
        name: ${{ inputs.cacheName }}
        authToken: ${{ inputs.cachixAuthToken }}
