[host]
username = "nix"

roles = [
  "boot-grub",
  "cachix",
  "openssh",
  "networkmanager",
  "docker",
  "docker/netbird",
  "netbird-client",
]

[network]
internalIp = "10.0.0.127"
externalIp = "140.238.221.62"
mac = "02:00:17:18:ab:39"
