[host]
username = "nix"

roles = [
  "boot-grub",
  "boot-efi-mountpoint",
  "cachix",
  "openssh",
  "networkmanager",
]

[network]
internalIp = "10.0.0.127"
externalIp = "144.24.255.32"
mac = "02:00:17:18:26:cb"
