netbird-setup-key: ENC[AES256_GCM,data:d3iQLFWLQgrYCmxd2VgzP2+3T/8Q1usCRTvrGUrPrMKmIIes,iv:9Us5B9PryT2rs7B0HA3idC8pCi9zCzu7DwKtWHU6684=,tag:8zpVekNFmk6QEwqoCqudfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybVBYRE1kVS9BMG10WHZY
            S2xwcmF4b01YSU1FajkySmxTL0trUUdvN2lRCkdIQTFYTUdwTnlZNEFkUGRrdjI4
            SEpqOThyRVpSdEhXT2dydU5idjBXQW8KLS0tIHZNdXhMWGYvRjNQNmRYWVI1MDEx
            WnVYQnAxakgzbTEwYlQ2OUVHYkxENjAKY/kX56lKD4lQXpqyJHDiDZ/7nPaTgth2
            2XzkEaVK8TPW9sFJ4JIZrOw/MQDsa2w0XketPqn4sXMqULFEqlzA/g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVjlHOEtsbzk2R1lWUmtG
            WkZDVWJjTDhUTzRhQVgxblJ4bDNQb1lzbkhrCmlPN2E2N2JTWVFoYWlMeExPaE9o
            VjJtcDY2ZWkzT3pqL2YvMWc4Tm5kWjQKLS0tIEpVU1ovUnJjTjQwbzhHL0UvMTFy
            S0U2OVBPOGJkOGlkUmpsV0laL2pQR1kKnZWhnvMdVVOKcZAimjWxk0QYX+yTXTAY
            JQoiYKGOQYo7NRw9BY6dYVrGeTR7bQqy8q2ZC6/KA4p3TUJ6hBT+PA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1my58mgua3z2tz9mfzurmnsvcncj68268wz85crw9mggxj8d0sq3qt0mskr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSGNqUWtTaTV1N2tnNHRM
            b1gvUXJWeXZSTHYzRE1zc2U3Q3hsUmtiNENNCjZsT2pNa3puNDN4VndlVU9wY0ht
            NDh3VkpZYXA1R0UvV0VlTktrZGRqL0kKLS0tIHVFaS9iaVNSTXFsWkFWVTNNWkFU
            b3pGTGEzKy8rR3AzYThEZVhRclhLaDAK2UyyKciCPdSTbDrJnLkgma6lztXA2XV5
            RReYSgjVvaUxt8fXylqTkP8V5+jRFvE5Ekk4PpOp8L43lZhBIjPV5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSG90WTVMZmZ3NnBjaVp0
            c2VHU1k2OTNXTDM3Nkk4SWxKZGFHdmtmTmhVClVSQmE2R2xKTDBaNmF2RExjVHIx
            MlNSSnlsNUtDUnErSkN4VWQ0cVRHL28KLS0tIEo2b053ZDRBZkF6bUVzWFJzVml6
            WmUzM1pCejVUT0dNcDhnalROMUtnM2sK/fz2YAog+K6wW7JT/EZjYs4XShhdDNn9
            dT/ZU25uHyFJ1K2RzGOVXz0sjVZha8KSBtt+/7W8TXZ+Wf0yWXVSlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-07-21T15:38:10Z"
    mac: ENC[AES256_GCM,data:zYh/Dz67ZJwzUwzNKkmaQk+eUU7seKANIvvUQIqTHmJMtdVosECHk5LITVA0OewMEuCnuealEJFAx1txJ2WzF4oaZKAyGGJJnGShkjfNo965Mx3Rr6zKlW2cfIqIgD//Tt8kosik6IDkYlGdbSgk4Dvb2Z5lf4TfNJB1gVDOKyw=,iv:6M+pH6n/s53YcKuMjCWP3AIe8FDT7PqblBbleXndyRk=,tag:X/2kDulyIQFHP6JwetEY0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
