netbird-setup-key: ENC[AES256_GCM,data:H2z+I3DL2GmIxm+xflUNvhUYOLdI/egx/8NdUWjEa7ZW1CMV,iv:LfA4c2ge1+qF+gyc/5VwdLlIpMvyqf9eup5tjcBJxnU=,tag:kTXXs97YlT5ZiGYD+L9irA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Rm1ZMkI0QzJKeUtPMlRl
            cnA2anF0U3NReHVGN1cvRGNuejBKS2pEbWtVCjNwRHVPTXkwVHVYbWphUFlQL0dU
            cFdBLzhzSytFWGxyZmMzYmlGcE5IRlUKLS0tIEV3S1NSdUdTZkNndnhoNENYT3RP
            YjU2dThZRzF0ZEJRejJzV3FaemdUeFUKwGQGiUFQHLHVdgrJn+oWqO9CtnBHjwFS
            YHpN39YMyEXYUZAGY3DvzKs0n+/gwa9izPFACODzgWsLIFNnQgn9Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTKzVKcklSWEZ2ZEdvYXAw
            ekp4NXo2Y2s0ZzBZSTh3T3lFUG9Nb3BYY3dNClk2NHhLdEQ3R0cyb2ZvbC80YmlU
            NEJ1RktxbEx3WmsremRGM2ZxL01wRkkKLS0tIHQ1NFdVTXQvT21oa2FIZ3E3WEoz
            cnVSRXhqZVZJanJDakVaWUtQeWs1dzQKxuZSBkKfqzEGEc46MDwC/QlOHjyDCifR
            UBLoE24NtrAexNcJRFjZv/dL0Fpgd56kpuujUL4nfO3SYg8iUDGujA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3gcq6a43fht8rt5k90k9ydlsr7d037lrqqx9lsyd92chfus6pss34q9jw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c2ZDMjFQZTVFUm54N1lY
            YjQwYTFQTzkrK01NT3RVS2x2dDJqSTFYVTF3CmdpYVdRZnFaNVB1VW5xZktndkRw
            enBlZTV2QmZxR2k5RUw3a2paL3FPUEUKLS0tIENlN3Z2dUR1V053cExnQU1OV01S
            YldVSjE1WWUxa0lCMG5ya3RmaW5ENFUKn2nsCMMI6n3jlSk5jpQAGBw1PGpqiFwC
            uUhzqX9k6mEI75W/lZk8f8Y9PcXhwdMldEjLVOymHpCAK6XrZMgQ7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2anlqQzBkUzVzd3VWK0dW
            RHg0bEQ4SXJaRm1UdStKQUw5UlV3enRPZG5jCmdGZzNLMXIrNXd0clFIU0I5a05C
            S29NRmJjTjI3YktteER2aVVRRnpyb1EKLS0tIHFqUnNNNGl6YzB3eCtOT2RmL1FY
            UWZ0MDFtdjRoaWZWZFByKy9RaGhBQTgKglth/2B8Q2KPqFepL47daZ90ak4pdzEm
            BJxnqW+3bySbq3mYXl8/aqwbszd/ALvhLEBTuxgQnSLpPqzg7cUTag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-07-22T11:45:46Z"
    mac: ENC[AES256_GCM,data:MnAdb6ZYYqtTgbMtZ1Khx7NwRdtF5SGjxm4DuF4vbSPrT95K1ozwAMHBQ2Hsqk0gs5A25vUxlknaCQNQ6RFsFaQk0v5OQ9JarlrfNUHE7cZyTqLgtb3ZxLmJmBsu2m8Bdw56xHhAKKt/i+0jy8huzBXOIVVHFes9Ia6LfIO7PHM=,iv:V1zQ/UbDhZf3WZ0DgSXMaO4eC84FFDiDTdTaYG7EeYY=,tag:ESWD8OiEnNsLhzuR9GzM0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
