# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cloudflared
  labels:
    app:  cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  cloudflared
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - image:  cloudflare/cloudflared #{"$imagescan": "cloudflared-scan"}
        command: ["cloudflared", "tunnel"]
        args: ["--no-autoupdate", "run", "--token","$(grep -A3 'cloudflared-token:' /etc/clouflared-token | head -n1 | awk '{print $2}')" ]
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /etc/cloudflared-token
            name: cloudflared-token 

        name:  cloudflared
      restartPolicy: Always
      volumes:
        - name: cloudflared-token
          hostPath:
            path: /etc/cloudflared-token
            type: File
---
apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
spec:
  repo: https:/releases.rancher.com/server-charts/latest
  chart: rancher
  valuesContent: |-
    hostname: rancher.yohanzbinden.ch
    replicas: 1;
    tls: external
    letsEncrypt.ingress.class: traefik
    ingress.enabled: true

