apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: portainer
spec:
  repo: https://portainer.github.io/k8s/
  targetNamespace: portainer
  chart: portainer
  version: 1.0.60
  valuesContent: |-
    service:
      type: NodePort
    tls:
      force: false
    nodeSelector:
      kubernetes.io/hostname: ocr1
    persistence:
      storageClass: local-path
    ingress:
      tls: false
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: <HOSTNAME>
          paths:
            - path: /
