k3s-server-token: ENC[AES256_GCM,data:kNqNdK6VRQ9HGe2+S2pOSJ9HOnT8lR4vHob4cK7Oy9i+U3F0tyL0UcXsWwbF,iv:Zqa/jjoy6zH3uw8pHtVQuIipURn+aPLHvj5juXNjg9Y=,tag:lqCZOCx+Ukdp4YDx2g9B9A==,type:str]
cloudflared-token: ENC[AES256_GCM,data:Uj26fPuHVK6DRfaZhMl3INdB6Oy24hrdTpkgmw/1TaFuimP1CgQtW6kT8QfLKHHgLco6BA/xDg/+fG3rZ9hSNkmdySisWdKAvfuWR87fg8tg1KQ0dskSeFVy2/3q1oOL++3SlmeiFVEprH0v30NoFEZ943lLvngWykuZJOkLbRp9vLasgTtRmgnTlVFVT+E6LVIcSrZPFzxOU9H/uv1fiLJT/NiKyft1PbBs6mfDuKrEaVckbnA+Bw==,iv:XRhMJn2vbuS+NY155guu7KY/yK7L6av2eb8wa+xa9CU=,tag:qJFcFcptGkeVqLdfwHmB6w==,type:str]
netdata-claim-token: ENC[AES256_GCM,data:vyIpi2BCYLNQC5wKIuzeHbAZ5WT7Wc3Z0SVljCiIwI5Tla0HNfAvkOeI6QWksb75WUXhgcetyv2bg4t4AFWbRfpoFjhwGDvDAFIMqY5aKPmHe9b7uJe+cNTSJUnFxk8kgicpOhR5p6fu5QtMool4pyx/wEI6BXBz55vyUqFXsrukq2bWfB3P,iv:nUYrMRR0Sw4t+A0Ur/fr1j7wrqBhGzxFM2D1ErY7cP4=,tag:oA9vTuJQLxx8dsI09NPcIw==,type:str]
homepage:
    cachix-api-key: ENC[AES256_GCM,data:cF2XUjf++mpBCs3aP4k/Axun3CbvUIaHWkhLaFNt5DBgaXg/Eot+uqLb2dfAC/Q5L8VVZ3jNavSfKOZ2hS4gLFwExSYyv4S1cGXUybiRXMdXLkdjkZozK5PGaGnCKHa2AUOSAGqqEsnL7zklGgbuIrVnGzsGRF8lMCSRgxL9EfPC6+6c7SRTQfUFVPW+k7HWpuJO8rA=,iv:+6TzfaroPuSL8PlGdKHGzUpjbWM3NhsQ1SPHKXmaDDo=,tag:iJgO589GM8gaTiHQCQOUwg==,type:str]
    argocd-api-key: ENC[AES256_GCM,data:GZOb+nw2HtBFLPZrfLD+bd1elLkWdI/vsjeMX3o5JORGzfV/mN2wsSPHOOlIUjbHywjipMGFXwwtBrPvj37sE3l4Ne86SFfSwOa4uPTyISiIkJscMPXWExXiKWcxUHSwra0LIDNDbMiZ9EZ08mUdA5DnNQ91ux1okuI8qvRdWuO2NgdfC/tjAfZFjtCiCG0cUBz92t+e8s+bPrrnSY7rt7XgTTCrEsjtSDfDo92ptvsZfdIzc33YEZr6qp2THk1VBRQhhhjxQAfGRIvuuqB1kHqq98ITBpE74YwP2xTlayVxAdvp74ZP1SAgrEUjJwdx,iv:ZK6CDmsJpPck8i0Fguo81ssLDWUjnJrW+Pprg8o97CU=,tag:IZF8FOlzsMO1+VNx0wrFQQ==,type:str]
    cloudflare-account-id: ENC[AES256_GCM,data:llDAXEl8yCcNiP/8deloudSDZy7qCB/pxlZXb45UV/o=,iv:BjiMSoU6vVVFTXNy8P6Ng2zwY4BCUWnI1IGAGjBLU2E=,tag:uOwc2/Cq5TuDlmvaktd+Vg==,type:str]
    cloudflare-api-key: ENC[AES256_GCM,data:MsiSCIFtuCrZ3Z2kiDNmbW2U6HMbPGOd2Q5ETZNSBbkHJcFy3oKGaQ==,iv:mdSKN0oNUJHlrWp4CO4E85peBst4bfUM7vHWuee3yc0=,tag:H3MKu8vWHQ3uInvkUMdr9g==,type:str]
    jellyfin-api-key: ENC[AES256_GCM,data:JoW+DMMPS/9uz9jq/AEQ5yiq/H3YdjUHwOMGAsiJVII=,iv:62n5G/FOxW/TW+SELNVGVGZkuEKEdbPNGLIbNHZAi1k=,tag:3izOueq+0Gf6jCWvCFebQQ==,type:str]
    jellyseerr-api-key: ENC[AES256_GCM,data:TDPFo6rUOL6vYiw3KXGKJAYn4t1SbNUkmSLes4C4fJxoGPDENuoftUKjA3Dx7ftFwDtgyW4SawWOIqx11U9UaoO/UGU=,iv:BjvbzDTpldMWdMXU72MFBq0rRtxb5QlTMB1ncOVFngs=,tag:vTt9AtYSqr6dEjYELcV0CA==,type:str]
    radarr-api-key: ENC[AES256_GCM,data:Ki1avSj+1B0b1BXCUHIwLFvq7S3yyG6TWSn9fOc7yxw=,iv:VImz+iJmnJDBwCN9aEdYOBip4WwkaEciRL0n1WL1CO4=,tag:AXLutNELj3hn6YE9AQomMQ==,type:str]
    sonarr-api-key: ENC[AES256_GCM,data:TfN2Gf6SCFfklilHkzp/4B1ZK4/yQGeM9gErPZnmav8=,iv:CPX7BZfv709F1rXAZ486arWAYsNuOUpjRZp3lhbIUjQ=,tag:fpKxKWBf4HjnP7NEWwiYxA==,type:str]
    qbittorrent-username: ENC[AES256_GCM,data:7NhG2AE=,iv:SREfYQ72+i5R8d22OkBAnCa1r8QheyqSPhzynNB69Qk=,tag:yvxiZX86QldaoPgOhYfBfA==,type:str]
    qbittorrent-password: ENC[AES256_GCM,data:jncKM/f0+nzjLgmgw3Q=,iv:gN03iwDSE9ecmC0supdMnMkZbTE9DiziisRZFC8h8tI=,tag:ReWiFeOJHj1JOyGeob3mGQ==,type:str]
    vikunja-api-key: ENC[AES256_GCM,data:axJIM3YO+sfZARvT75WbF4bLl5zke4CA9TOPsbzIlqV2XdwW42SOjmTwMA==,iv:Fc5YIWoM05k8Q8nVK+EPb8N63edPu3kHPZSa8XaoDhw=,tag:MveC4E3GBnZplLv5JmDjCw==,type:str]
vikunja:
    user: ENC[AES256_GCM,data:LSX61kIQSA==,iv:cHWrvmVZ0DIAFMZEVwDRva3iUSogC8jwizAwGsC1hpY=,tag:7L6a6asNcyLntGOe5+2Dmw==,type:str]
    password: ENC[AES256_GCM,data:k/oWQmSo+Ti4glWyCvFsJ6hyZVY=,iv:/zjGSoS/5wT0674tz2UFPOsnPsw6wfxP4/LEm6W6+Qc=,tag:sHPUHJv0lbdqXMB/5gr9uQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZE1XTkF5cE1wOVorQnRN
            OVJOdENMcGlGQjl0dWdJQytpT01JVTIwb2pjCm82aWxMQXlNUHdNdHJPQ25sZEtV
            Y1NCS0hoNUF3QmJ5amdoT3V6Wm1MQjgKLS0tIE9xZUQ2YU9yWXExWVFUUEc1N2R2
            ZFhVOFZmS0F2aXRRT2drQ2lCNkNKc2sKPaarh39ZBqX8YIGVQEHU9Oq0b44gga0m
            9tSptX/YseUl4K4fSXaN0XdYfJRjICrdW1Sha76iNigbz7m6zj8b4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRHE5NVV3K09yUVVzbldv
            K2ZRWHhvWmRnTEd2Q1k2Ylh3RkY5SFgwVlZNCnUrcUIxMjV0SHlta1VHMk04cVhq
            RVJjRFk3SlZNWkMxQitnMHJDWGZZWFEKLS0tIFk2c1FFZHU3dTJPamZ3dzhwbFZZ
            eTA0dEo2Rm9ndzhPeFNvdzBieFd3djgKzU/WHU9VWKFFWYLu8S+l2hIYE1GDxc0x
            94Dj60yPJH9hCV8H7Bmu02gN0JGc59njFsGiNtOabEKiCph7mbstzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1my58mgua3z2tz9mfzurmnsvcncj68268wz85crw9mggxj8d0sq3qt0mskr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UVNSNVhkSEp5N1N3TlBp
            d2lrVTdpUWpVQVZSVE5rUmIwT0E1ZUY4NW1FCk9zMDViMUUyQzFLZzBSYTYvZit3
            emNwYWh1V1BSN2c2Z1lWUUNCRXhXbXMKLS0tIDdIQWVRenl2by9DUTU5VGYxU1k4
            OHNQOXVlSmowbVVVZ2M4bmVZbzM4NjQKZ2fT9C7MQCslUKmIhc7l6KIpBwW2AETI
            R8S/cH0CHtYb02V0RZHPA/M/jQVKZmEtzHqCJebLDLClqnZmcqj0Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMVY5dXp3TXlwa2ZNanFn
            aVN0eWpQcEliNHduMXVZbi83eE1wckNlNG5NCnJKbGlralZ6TDRYTTdaeFh5WGo2
            ME1EZEE3eDlnb2xZQjJWdkg2SW1sZFEKLS0tIG5tWWJGTm5lTlZSUVNsMnZNUUoz
            ZWtZd3ExWUkyNmt5OXdpM3ZRNWZuQ1UKC360w9cbZJjBv+Ptq4ACl3MfoRaDiU9o
            fBQvtgQo5u+qXfibjxsZ2CWolCeSulSTXw87eMKMwr/NAlJzHUhXvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-07-17T14:31:27Z"
    mac: ENC[AES256_GCM,data:I0347k3G2LGl4V3jAug63wHqvGba4NapjyaYS+EHfuqqtPcsNRUsuaTfMVFiDgoOdpdNjvhzLNO+9sX0OCpIMKwQLuQZtjuv4zFikqZH2KLmOoyIr9d4V3/17R7xOZ6//9/MpgztVvw/uCmoekG66atariUR8xKNdh8+Se4WziQ=,iv:T/ia2RDXOsMzSMPhI29A9k+4hfEe56X86hQ2ZplLit4=,tag:jnKE7V7+EyngyIyxCMQ2Ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
