netbird-auth-secret: ENC[AES256_GCM,data:o1/0do2xsTp/MyUd1kTiEyoK3uhFYS3e2hlip2m+yyAjCb7fh0K8yXG7AQ==,iv:OuwbpPuILxjm00KGI15Ag+N01R3Zn1xNaPptOpuQoMI=,tag:SQFz6RUsGAVJJlcps6AeAw==,type:str]
netbird-encryption-key: ENC[AES256_GCM,data:1PVbIAhvamtpL/f4SLkAxW9Lox0Mm4iiZcVPgK4UJbnkHqXLER9uTDlXmyg=,iv:wOlj6u6uPOnk7bwqSuDyXhibzN92WQkg1fiZjmFoEXo=,tag:7BZceZ0nH6pv7yFHepU88g==,type:str]
netbird-proxy-token: ENC[AES256_GCM,data:07OtO+N4zXVd0o4nKcyJuiNkR0dqfE0/DPGOjblLa7D+K70hz1IAiA==,iv:YMVnazbWKWvsZ8jqe7NTawSF235FWNWcQRkxC3VIQZM=,tag:V4hanY9+UsilNsqbzlMsLA==,type:str]
netbird-crowdsec-bouncer-key: ENC[AES256_GCM,data:L4PUqh+EBdLqELJkAQeuICvmxcoOojDiWJrFsoJCZtr0SOABimZmHxPBxw==,iv:+x5rOxRacfiCVKT4Oto9swv2b+SkFBtPxYQ4Gg9Po+g=,tag:qBj8W2G4jKh94pL417X0Jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbzUrVkFKeXZtQXIzWEU1
            YStjSFBKSEx4cy9lb21PVTR5TXdKdjVsYW5FClVzQXM3R1lvOGdBTjQ0amh4WjB0
            OVpCN1N6TVFmTFpZUk5QU3lNUmNvSVkKLS0tIEhTUGFiUFFieTNZYjFPT3o3RmUx
            MGYzVkVIakVhQXlTL3kvd1ducitwcGMKlcVK0q8IjjuGTs8scqRa7we6nyTy6vbm
            PTiByjproGMvBD89BAE47hBmBuGToppSJqAOLH9ZcbC5T7AFfo0qbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZODdTdGhqcHZsVWFnVmdN
            MVhyUVEvMFozRHV0aWpaRElIVzZqRnJGK0I4CnFtbFo3cE9nVGR1WXIyRFhUbmRS
            dHRQcjh4akJKQ2VsaE1jVHhvd3U2ZEkKLS0tIFpzSHJwQjNxR0VlRklvd01uWWx3
            ZVFTc0hzZ2xhOHNtNmNXUlVVTFZIWkEKZTe2/TKr6FZOsz3eiDDsfqWBfxGZ6Vwe
            TDZT0no8JY3fQzSGAS95BWXa/k7o6ROOVMDaxRVk8JTZJSYhUJI1Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m3gcq6a43fht8rt5k90k9ydlsr7d037lrqqx9lsyd92chfus6pss34q9jw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMUZIL3NHakJuVDVBVEp5
            eXZmUEFGY0htTHVWSFgyaXFWSENwN250ZTNZCnhpVkF3UjNhYnd6NVZZSll4ZmFu
            ZlBWOGxWL09RWVd3b0pzVUtId0ZzL2cKLS0tIHp1R3V2VDVvY2xROVEwNkhXanly
            WlN4MDJ5RTBRRlZ5b3N5eW5MZU50TVEK+RsOHnTOf3Gf3n5/icxNGoQ3bw9KuV6r
            4Ceyrlur2z/elmY02ubDkIY3korEN3V7Kc7Ou1wgkKyXNRJ/q6SnYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbHBBUFQ3VEdHZzF2VG5a
            dlBweG5yUEYydHA5QllWNndXRXJxMU9kNG5rCnNYUmlKYmZYd09LeTl5clR0R1Fh
            bEIwLzREdCtrTmc2NTdRbVB4dUNFd2MKLS0tIEsyWVRBQVdaTktSWnlLNThabk8r
            bWl2bEdzV2dWU29uTU1VZUdhRi8vZWMK0wWyw4qbusP0ZvH0dRXQQB5ltAuzDlaV
            vTqFwVXvlyMTIKp/98m2CpbSjehyjSjXGgL0V7rPV5EdS0rtLxv+Hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-07-22T11:45:33Z"
    mac: ENC[AES256_GCM,data:BCrctri+1KIP442IjBq8cMBqFFpsutz07+kosm5QiklJzvvRqFGEmDeRcfonUBImVg3WlFAD+kCtJGjktWCSCPANj4i/vSDPpYk3DCmyLGYuDftq3n5CskAWRmnw0EkiuOxQarSLL1DQEqkhs9dFoC54vero7jVYB+NVdRyFh68=,iv:0aYUix0iHDGo+ewDtEGNUIaBK0sNqd1vmJjw+Nr9u1Y=,tag:WSta4+EOOQg+5awepyDmDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
