netbird-auth-secret: ENC[AES256_GCM,data:o1/0do2xsTp/MyUd1kTiEyoK3uhFYS3e2hlip2m+yyAjCb7fh0K8yXG7AQ==,iv:OuwbpPuILxjm00KGI15Ag+N01R3Zn1xNaPptOpuQoMI=,tag:SQFz6RUsGAVJJlcps6AeAw==,type:str]
netbird-encryption-key: ENC[AES256_GCM,data:1PVbIAhvamtpL/f4SLkAxW9Lox0Mm4iiZcVPgK4UJbnkHqXLER9uTDlXmyg=,iv:wOlj6u6uPOnk7bwqSuDyXhibzN92WQkg1fiZjmFoEXo=,tag:7BZceZ0nH6pv7yFHepU88g==,type:str]
netbird-proxy-token: ENC[AES256_GCM,data:RcrlCXP7D6ql2Og=,iv:e6cF+a3t0rp8PcIXvAv5Utuzp8vQ53Kww/a8JOGsY+o=,tag:ljLoIzaVKDtO3dnlgnBkXA==,type:str]
netbird-crowdsec-bouncer-key: ENC[AES256_GCM,data:F7eaYUncvLZdihLliIAB0/HHFJ+Xli+dP+8ypEJYxiSKRMzR+nUcpdD/vto=,iv:+yZBuERvya09RPUTNo4TwXupcb5lgLljUrRojyk7jbk=,tag:lBA7ZZAd8CqV699i1AClQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT1picnNud2VLSVBzWEhv
            Q2luOE1yazhOTXBlUFcrNzFIdVNpV2VsWTFRClg2MEVuRFBTTkZlS1RSYXZ6S1Vo
            UlV3bEhVSXlJRERtMW5PWDNwMVJQQ3MKLS0tIEk4bGhFTFdRT2JFMjZ2eUh2N25z
            YllUeGtEWm5RYmkvbG91VHovci8remMKUqetvhvBRcM3/P1Q/Ru39o6ec19m8bUT
            A9esdOv88QmgKfuELKdT7tdFxv9p3TXfN1FVtUsYOcxpM8fsLIy7VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r46e0k2t89dpqf93vqerkatq9jevl8pj2lhv7d06axw5q3svs53sgy2da8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ00vL003L0JldE5VTXhU
            K0gyN3JGMDUxb2JVdkdQejVsaFIzeFBmK21rCmljMWhZREh3RWdxdW8vVXlpZjNH
            ZVg1U0lrWGhTRHYwdHJmZkRrdUFoZ0kKLS0tIElIemQvT0ZMSW5uN0RZZVQ5UVBD
            ZlpuVXFGTlZtdjg5MTdWelcvNkF3U00KkBryobFF5wJCzolrAPOeWmBBVwvs4sHO
            8XPnioNuPOaw1/MDr4rl3o2+9WhBqwFIoaAMNWQLLzNJ7y78qkmqBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1my58mgua3z2tz9mfzurmnsvcncj68268wz85crw9mggxj8d0sq3qt0mskr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM2owZ2lqR3NGQnNFalcr
            OEoxVUI2SHZlR2VPKytPZnY4Wkhzd3NZbkRzCjRtNktmU3ZmaTN1ejVId3VvVHph
            TzRUSTVhcVRpRWhJRU9hN091QURBdVUKLS0tIG9zMUNlUmt4TG44V2FSZXdYYlU5
            ZzArUjFyaGh2ZHlmVG9GV09jWkxPN2cK0+SVM9mTGRFNAEp15S6NajRBlgl0Z701
            jRjKrQnPhdOv0XEaBrzYLJ7h8NBiNEnrQGkcXT1spERDUA+cfrWJaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wyggh6p77q5g00e784psmvtm2m8j96nsnzry4cpj9g70agexmatquped2e
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bHJGcUQ3dHRXZ2UvU2JK
            b0piblRzSTVkRkV0THRoU0VGdzJqejVwZzF3Cnd6VCswUFdzdm5BNExMSzRvdXNC
            Q3VqQTFTUWpqU25SQjJveThhanRIbkEKLS0tIHMyMm1NQ1JHWmkwblcxTTBaVXhT
            QlJZSUhwRUdFZURrZytpN2p2c0oxSGMKqOy8VCPiI9msmDWUcy4ToBcUt3OEpP37
            jdGu2h86WM1Bec+OzAq3+/TpuRZ+0L3+1v+vUR7zcpN0KPa9et9Xkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1lfpdcqsgcsa294c0kypu6ny5syavfp9ls3cj8mf06awrf7237pssazlfan
    lastmodified: "2026-07-21T12:10:26Z"
    mac: ENC[AES256_GCM,data:I7T+j8RLDf/8xR5JwGpSqFRyISHgmLrooL3BlRbHvl99JeqkAeDAUfcIOWgfjrz4MIPwhWJ6JDEg1N/fSyyIEl1YK9a5HVjyPvlZUkHUt6QaJNOxrEg0hJNbFuXjwSr6MW7HwqocULMlxNk2ABCxzD3eRjECStug3Vfvk01wm6k=,iv:DCG6mC7qv9KxN0NmLElfDfUZj8LA2Gkn6ha6XJj53+Q=,tag:RrDmYiwqRLBKb3/Tv9MA9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
