name: Build host reusable workflow

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
      cacheName:
        required: true
        type: string
      setup-qemu:
        required: false
        type: boolean
        default: false
      extra-nix-config:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ github.event.inputs.hostname }}
    outputs: 
      ${{ github.event.inputs.hostname }}: ${{ steps.agent.outputs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3
        if: github.event.inputs.setup-qemu
      - uses: cachix/install-nix-action@v25
        name: Install with extra config
        if: github.event_name == 'workflow_call' && github.event.inputs.extra-nix-config != ''
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"
      - uses: cachix/install-nix-action@v25
        name: Install
        if: github.event_name != 'workflow_call' || github.event.inputs.extra-nix-config == ''
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: ${{ github.event.inputs.cacheName }}
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        id: agent
        run: | 
          out_path=$(nix build -L --print-out-paths --accept-flake-config .#${{ github.event.inputs.hostname }})
          echo "Built $out_path"
          echo "${{ github.event.inputs.hostname }}=$out_path" >> $GITHUB_OUTPUT

