name: "Build and Deploy"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CACHE_NAME: homelab-yohan

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "null"
    outputs:
      cacheName: ${{ env.CACHE_NAME }}

  ocr1:
    name: ocr1
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    secrets: inherit
    with:
      outputName: ocr1
      cacheName: ${{ needs.prepare.outputs.cacheName }}
      setup-qemu: true
      extra-nix-config: "extra-platforms = aarch64-linux"

  rp:
    name: rp
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    secrets: inherit
    with:
      outputName: rp
      cacheName: ${{ needs.prepare.outputs.cacheName }}
      setup-qemu: true
      extra-nix-config: "extra-platforms = aarch64-linux"


  tiny1:
    name: tiny1
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    secrets: inherit
    with:
      outputName: tiny1
      cacheName: ${{ needs.prepare.outputs.cacheName }}

  tiny2:
    name: tiny2
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    secrets: inherit
    with:
      outputName: tiny2
      cacheName: ${{ needs.prepare.outputs.cacheName }}
