name: "Build and Deploy"
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:  # allows manual triggering
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Homelab
      url: "https://app.cachix.org/deploy/workspace/homelab-yohan"  # ⑴
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v3                                 # ⑵
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/install-nix-action@v25
        name: Install
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"             # ⑶
      - uses: cachix/cachix-action@v14                                    # ⑷
        with:
          name: homelab-yohan
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Check
        run: nix flake check
      - name: Build
        run: nix build --print-build-logs .#cachix-deploy-spec            # ⑸
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        run: |                                                            # ⑹
          cachix push homelab-yohan ./result
          cachix deploy activate --async ./result
