name: "Build and Deploy"

on: # yamllint disable-line rule:truthy
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - main

env:
  CACHE_NAME: homelab-yohan

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "null"
    outputs:
      cacheName: ${{ env.CACHE_NAME }}

  ocr1:
    name: ocr1
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    secrets: inherit
    if: ${{ github.event_name == 'push' }}
    with:
      hostname: ocr1
      with-nothing-but-nix: true
      runs-on: blacksmith-8vcpu-ubuntu-2404-arm
      cacheName: ${{ needs.prepare.outputs.cacheName }}

  surface-nix:
    name: surface-nix
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    if: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit
    with:
      hostname: surface-nix
      runs-on: blacksmith-8vcpu-ubuntu-2404
      with-nothing-but-nix: false
      cacheName: ${{ needs.prepare.outputs.cacheName }}

  rp:
    name: rp
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    with:
      hostname: rp
      #with-nothing-but-nix: true
      cacheName: ${{ needs.prepare.outputs.cacheName }}
      runs-on: blacksmith-8vcpu-ubuntu-2404-arm

  tiny1:
    name: tiny1
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    with:
      hostname: tiny1
      with-nothing-but-nix: true
      cacheName: ${{ needs.prepare.outputs.cacheName }}

  tiny2:
    name: tiny2
    needs: [prepare]
    uses: ./.github/workflows/build-host-reusable.yml
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
    with:
      hostname: tiny2
      with-nothing-but-nix: true
      cacheName: ${{ needs.prepare.outputs.cacheName }}
